### ISSUE TITLE
Cannot change styles

### ISSUE THREAD

**Issue by JCavallo** [nvim-lua/diagnostic-nvim#44]
Hi @haorenW1025 ,

I am trying to have either Floating / Virtual text styling work properly, but nothing I tried worked yet.

I've set all highlight groups like this (tried a lot of configurations, but nothing works) : 

```
        hi! LspDiagnosticsErrorSign cterm=bold ctermfg=196 ctermbg=235
        hi! LspDiagnosticsError cterm=italic ctermfg=196 ctermbg=235
        hi! LspDiagnosticsErrorFloating cterm=italic ctermfg=196 ctermbg=235
```

Checking that the values are properly set looks good :

```
:hi LspDiagnosticsErrorFloating
LspDiagnosticsErrorFloating xxx cterm=italic ctermfg=196 ctermbg=235
```

However, everything (signs, virtual text, floating, etc...) seems to use an autogenerated style based on my current colorscheme.

Maybe linked to https://github.com/nvim-lua/diagnostic-nvim/issues/43

**Comment by haorenW1025** [comment]
Hmm I never tries to modified the floating and the sign highlight so I don't know how to do it...Maybe asking it in neovim gitter will help.

**Comment by Iron-E** [comment]
I have noticed this behavior as well while developing a colorscheme not too long ago.

My fix was to put all highlighting information at the very last line of my `init.vim` ([here](https://gitlab.com/Iron_E/dotfiles/-/blob/master/.config/nvim/init.vim#L30) is my exact config; my colorscheme defines the `Lsp`* highlight groups). I am able to reproduce this issue without `diagnostic-nvim` consistently by changing the location of my `highlight` commands. Can you make it happen without `diagnostic-nvim` too?

It seems like whenever the LSP's settings or changed / when it initializes the highlight groups are reset. If putting the highlight commands at the very end of `init.vim` also works for you then I'll create an issue on neovim/neovim since that would make two people who can verify the fix.

**Comment by JCavallo** [comment]
I've never managed to have the hightlight work when I set them myself.

However, I tried with your colorscheme (`highlite`), and they indeed worked (as they did work with some other colorschemes like `dracula`).

Maybe there is something that clears them if they are not defined in the colorscheme ?

**Comment by JCavallo** [comment]
Investigated a little more, and I think I got it.

Basically, if the groups are not defined in the color scheme, they are automatically set based on the values in the colorscheme.

I made it work by plugging in an autocmd on the Colorscheme event:

```
    function! SetLSPHighlights()
        hi LspDiagnosticsError guifg=#FF0000 guibg=NONE guisp=NONE gui=NONE cterm=bold
    endfunction

    autocmd ColorScheme * call SetLSPHighlights()
```

So far this seems to work as expected.

No relation with `diagnostic-nvim`, so I'm closing this.

**Comment by Iron-E** [comment]
Seems like it's definitely unintended though. The other highlight groups generally don't behave that way… I can imagine the intended behavior is that if the groups were not defined _at all_ (not just by the colorscheme) then a default would be provided. It seems strange to _have_ to use an event just to `:highlight` something.

I also looked for an issue on neovim/neovim to match this one but all I could find was [this](https://github.com/neovim/neovim/issues/12162) which doesn't fit.
